# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# Install jenkins package
- name: Install jenkins package
  yum:
    name: jenkins
    state: present
  become: true
  environment: "{{environment_vars | default({})}}"
