# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-jenkins-repo.yml
- include_tasks: install-jenkins.yml
- include_role:
    name: configure-jenkins-nodes
    tasks_from: configure-jenkins-server
- include_tasks: enable-jenkins-service.yml
- include_tasks: start-jenkins-service.yml
